{'app_version' : 'test.006',
'config_file' : 'seolh-ca-config.yaml',
'back_end' : 'default_backend()',
'initialized' : 'yes',
'common_name' : 'TestRoot1',
'subject_alternate_names' : 'ca.local',
'email_address' : 'test23@local',
'organization' : 'Home',
'organizational_unit' : 'Test',
'city_or_locality' : 'West Sacramento',
'state_or_province' : 'CA',
'country_name' : 'US',
'serial_number' : '298784229688508877703079465624509844448',
'algorithm_name' : 'secp256r1',
'hash_name' : 'sha256',
'certificate_lifetime_in_days' : '1',
'private_key_file' : 'root_private_key.der',
'private_key_format' : 'der',
'private_key_password' : 'null',
'root_certificate_file_name' : 'root_cert.der',
'root_certificate_format' : 'der',
'fqdn' : 'ca.local',
'ip_address' : '127.0.0.1',
'database' : 'null',
'port_number' : '80',
'auth_psk' : 'afs9dfi9pj34wr09'}